# Generated by Django 5.2.4 on 2025-08-13 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='expense.expense'),
        ),
    ]
