# Generated by Django 5.2.4 on 2025-08-13 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userexpensespayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesparticipant',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseparticipants', to='expense.expense'),
        ),
        migrations.AddField(
            model_name='expensesparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('title', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='expensepayer',
            unique_together={('expense', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='expensesparticipant',
            unique_together={('expense', 'user')},
        ),
    ]
